### PR TITLE
Differentiates undo actions from user actions

### PR DESCRIPTION
**Pull request by taylorhadden**
I added a new 'undo' source and use that when calling the undo/redo actions.

I have code that runs as the user types. It applies formatting and queues up auto-complete and auto-update behavior. Flagging undo as separate from normal user input lets me skip those pieces of functionality, preventing loops where an auto-complete behavior triggered by a text change is undone and then re-triggered, causing it to happen again.

I added a new `Source` instead of using `Source.api`, as I assumed 'api' was being used for network sync activity.

### CODE REVIEW

**Comment by jacwright** [comment]
This seems like an incorrect approach since an undo operation is initiated by the user and is therefore a user's input/change.

A situation where this could go wrong is say typing 3 letters "ex" autocomplete to "example" and the proposed change allows an undo to go back to "ex" without triggering the autocomplete. However, what if the user has the text "exrta" and deletes a few characters to "ex" in order to fix their spelling to "extra"? As soon as they hit "ex" the autocomplete expands to "example".

We have 2 modules that handle similar situations in 2 different ways. Smart quotes and smart entry.

Smart quotes listen to the "changing" event before it is committed and look for any quotes being added to the editor in the change and converts them to the "smart" version. This is not undoable because it changes the character before the change is committed.

Smart entries listen to the "change" event and will make an additional change after the first is committed, allowing for an undo to happen. Thus, typing "--" will commit the change first then immediately become "—" (long dash), but an undo will revert it to "--". The module does check the change operation to see if it is a text entry by looking at the Delta operations (https://github.com/typewriter-editor/typewriter/blob/05d9392d1cbc6be3b5a9d47512a7ea57b1686668/src/modules/smartEntry.ts#L161-L168). This ensures an undo doesn't simply re-run the change. Perhaps we should expose this function as a utility for other modules, such as autocomplete, to use, allowing them to know when text was entered by a user and not arrived at by pressing delete or undo.

**Comment by taylorhadden** [comment]
I can look into that approach.

In my particular case, I want to be doing some processing both when characters are inserted and deleted, but not when undone. I reached for `Source` because it was the easiest way to get what I wanted. Perhaps `Source.user` is too broad? It would be nice for modules to be easily able to flag a change as coming from them.

What do you think about adding a function to the history module, e.g. `history.isApplyingHistory()` that returns the current state of its `ignoreChange` boolean?

**Comment by jacwright** [comment]
It may be useful to go beyond that and identify the types of change. E.g. `input`, `paste`, and `history` would be some. `drag-drop` for images or `toolbar` for something being changed via a toolbar. Do you think these would be useful? They could be optionally passed into `editor.update()` and added to the change event along with source.

Or, they could be sources, and all sources are assumed "user sources" except for `api`. I like that actually. Let's do that. The default will be `Source.user` for those who don't want to set it to something specific, but official Typewriter library code will always set it to something more specific.

Thoughts?

**Comment by jacwright** [comment]
Would you like to make the changes? We could add the following to the `Source` Enum:

* `history`
* `input`
* `paste`
* `toolbar`
* `drag-drop`

In `history.ts` and `Editor.ts` check that `source !== Source.api` rather than `source === Source.user`. Then in `input.ts` and `keyboard.ts` we can change the source to be `Source.input` and in `paste.ts` we can change it to be `Source.paste` and in `'history.ts'` we can change it to be `Source.history` (rather than "Source.undo", since redo is also a history action). We can update the changes via toolbars to use `Source.toolbar`.

Do you think we should change `Editor.update(change, source: Source = Source.user)` to be `Editor.update(change, source: Source | string = Source.user)` (and other APIs that feed into this one) to allow for other sources not part of the Enum?

**Comment by taylorhadden** [comment]
Apologies for the delay. I like this! I will make these changes promptly.

**Comment by taylorhadden** [comment]
The suggested changes have been partially implemented in PR #84.

**Pull request closed without merging**
